version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GITTEST_5125Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
services:
- serviceName: project.siqa_gittest_5125.integrations:AlertsCRTandERT
  packages:
  - name: SIQA_GITTEST_5125Project
    version: "1.0"
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 11.1.0.0.2100
