version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GITTEST_5125Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
- name: TPP_services_in_FCS
  gitServerName: SIQA_KVV_IBM
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
services:
- serviceName: project.siqa_gittest_5125.integrations:AlertsCRTandERT
  packages:
  - name: SIQA_GITTEST_5125Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 11.1.0.0.2100
- serviceName: project.siqa_gittest_5125.integrations:deepclonetest
  packages:
  - name: SIQA_GITTEST_5125Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 11.1.0.0.2100
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 11.1.0.0.2100
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2100
